class InGameMessages {
  static final List<String> igmessages = [
    "MAXED OUT MY INVENTORY SLOTS... FOR SNACKS!",
    "HUNTING BEHEMOTHS IN-GAME, ORDERING PIZZA IRL!",
    "BEWARE OF MY VIRTUAL PAW SWIPE... AND MY REAL ONE!",
    "EATING ASTERA JERKY WHILE WAITING FOR THE QUEST TO LOAD!",
    "FLEXING MY DIGITAL MUSCLES... AND MY GAMING CHAIR!",
    "COLLECTING DIGITAL HERBS FOR THE VIRTUAL POT!",
    "ON A QUEST FOR THE BEST GAMING SNACKS... AND LOOT!",
    "HOLD MY POTION, I'M DIVING INTO THE DIGITAL ARENA!",
    "UPGRADING MY GAMING RIG, LEVELING UP IN REAL LIFE!",
    "WEARING MY GAMING HEADSET... CAN'T HEAR MONSTER ROARS!",
    "FIGHTING OFF SLEEP, LEVELING UP MY HUNTER INSTEAD!",
    "READY TO FACE THE VIRTUAL WYVERNS, COFFEE IN HAND!",
    "DIGITAL INSECT GLAIVE READY, PIZZA CUTTER ON STANDBY!",
    "MASTERING THE ART OF GAMING, HUNTER STYLE!",
    "NO QUEST FAILED, ONLY STRATEGIC RETREATS TO THE FRIDGE!",
    "VIRTUAL PALICO ON MY LAP, REAL CAT ON MY KEYBOARD!",
    "EQUIPPED WITH A GAMER'S INTUITION, UNDEFEATED!",
    "IGNORING REAL-LIFE TROUBLE, FOCUSING ON GAMER STRUGGLES!",
    "VIRTUAL AMMO STOCKPILE CHECKED, REAL SNACKS ACQUIRED!",
    "SWITCHING ARMORS IN-GAME, SWITCHING PJs IRL!"
  ];
}
