class RegisterMessages {
  static final List<String> rmessages = [
    "FORGING A NEW HUNTER'S ID... SNEAKING INTO THE GUILD HALL!",
    "CRAFTING A VIRTUAL FELINE COMPANION... NEED A PROGRAMMING PAW!",
    "SUMMONING THE REGISTRATION RATHALOS... CAPTURED IN DIGITAL PIXELS!",
    "TRAINING THE DIGITAL POOGIE... DON'T TOUCH MY MOUSEPAD!",
    "SHARPENING MY VIRTUAL HUNTING HORN... SERENADING THE CODE!",
    "LEVELING UP THE CYBER-TRACKING SKILLS... SPOTS A NEW USER!",
    "SEARCHING FOR THE PERFECT AVATAR... MUST LOOK HUNTASTIC!",
    "FUSING ARMOR MADE OF CODE... +50 DEFENSE AGAINST VIRUSES!",
    "HUNTING DOWN THE ELUSIVE USERNAME... IT'S WYVERN-APPROVED!",
    "CRAFTING NET-PROOF PALICO GEAR... FASHIONABLE AND FUNCTIONAL!",
    "SURVIVING THE DREADED PASSWORD QUEST... DON'T GET LOCKED OUT!",
    "DODGING CAPTCHA LIKE A TRUE NINJA... UNSEEN AND UNDETECTED!",
    "SCALING THE WALLS OF FIREWALLS... INVISIBLE IN THE CODE MIST!",
    "SOLOING THE REGISTRATION QUEST... NO TEAM NEEDED!",
    "SETTING TRAPS FOR TROLLS... ONLY FRIENDLY HUNTERS ALLOWED!",
    "TAMING THE WI-FI BEAST... NOW IT OBEYS MY COMMAND!",
    "CATCHING PIXEL-PERFECT FISH... FISHING ROD OR MOUSE POINTER?",
    "NAVIGATING THE DIGITAL JUNGLE... WATCH OUT FOR SCRIPT MONKEYS!",
    "DISCOVERING THE SECRET HUNTER HANDSHAKE... IN CODE LANGUAGE!",
    "LEVELING UP TO G-RANK REGISTERED HUNTER... THE HUNT BEGINS ONLINE!",
  ];
}
